Add dates disabling/restriction props
onesine/react-tailwindcss-datepicker pull request #30
Opened 2023-01-06 20:24 UTC by NoahMLoomis

Props added:
- minDate: The minimum date that can be selected (inlcusive)
- maxDate: The maximum date that can be selected (inlcusive)
- disabledDates: An array of date ranges to be disabled

I think having separate props for minData/maxDate and disabledDates improves clarity.

@onesine How can I update the Documentation site?

Also @JefteCaro thanks for creating the playground, it made the DX 10X better

2023-01-06 22:16 UTC, onesine commented
> Props added:
> 
> * minDate: The minimum date that can be selected (inlcusive)
> * maxDate: The maximum date that can be selected (inlcusive)
> * disabledDates: An array of date ranges to be disabled
> 
> I think having separate props for minData/maxDate and disabledDates improves clarity.
> 
> @onesine How can I update the Documentation site?
> 
> Also @JefteCaro thanks for creating the playground, it made the DX 10X better

It also offers more possibilities. We can even combine everything.

2023-01-06 23:26 UTC, onesine reviewed
Can you make these changes?

2023-01-07 01:55 UTC, JefteCaro requested changes

2023-01-07 01:55 UTC, JefteCaro commented on package.json
> +    "name": "nloomis_react-tailwindcss-datepicker",
Thanks @NoahMLoomis 

For me, too.

All are good.
Let's just keep the latest package name and version

2023-01-09 13:24 UTC, NoahMLoomis reviewed
Finished self-review

2023-01-09 13:25 UTC, JefteCaro approved these changes

2023-01-09 13:32 UTC, onesine approved these changes

2023-01-09 13:50 UTC, onesine commented
Merge won't happen if we don't resolve the conflicts

2023-01-09 13:54 UTC, JefteCaro commented
@onesine Yeah

@NoahMLoomis 
Thank you for the fix.
Can I ask to have the `yarn.lock` be removed from `.gitignore` in the mean time, so the `yarn.lock` file can be added to your commits?

2023-01-09 14:04 UTC, onesine commented
Yes, in fact, I'm working on it right now.

2023-01-09 14:23 UTC, merged